# Generated by Django 5.2.17 on 2026-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=40)),
                ('kind', models.CharField(default='lookup', max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('data_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['district', '-version'],
                'unique_together': {('district', 'kind', 'version')},
            },
        ),
    ]
