# Generated by Django 5.2.17 on 2026-10-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='storage_key',
            field=models.CharField(blank=True, help_text='Object key in the B2 bucket; empty = local file.', max_length=200),
        ),
    ]
