# Generated by Django 5.2.17 on 2026-10-02 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('poultry', 'Poultry')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('target_qty', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('met', 'Target met'), ('lapsed', 'Lapsed')], default='open', max_length=10)),
                ('buyer_note', models.CharField(blank=True, max_length=200)),
                ('agg_lat', models.FloatField(blank=True, null=True)),
                ('agg_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('poultry', 'Poultry')], max_length=10)),
                ('breed', models.CharField(max_length=60)),
                ('sex', models.CharField(default='Mixed', max_length=10)),
                ('age_months', models.PositiveSmallIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ward', models.CharField(blank=True, max_length=80)),
                ('public_lat', models.FloatField()),
                ('public_lon', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending moderation'), ('live', 'Live'), ('sold', 'Sold'), ('removed', 'Removed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'species'], name='market_list_status_c4c8fc_idx'), models.Index(fields=['public_lat', 'public_lon'], name='market_list_public__a75f4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PoolCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('age_months', models.PositiveSmallIntegerField()),
                ('ready_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('rejected', 'Rejected')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='market.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
