# Generated by Django 5.2.17 on 2026-10-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
