# Generated by Django 5.2.17 on 2026-10-02 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('animal', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOp',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=20)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('result', models.CharField(default='applied', max_length=10)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_ops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
