# Generated by Django 5.2.17 on 2026-10-03 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', models.JSONField()),
                ('area_ha', models.FloatField()),
                ('centroid_lat', models.FloatField()),
                ('centroid_lon', models.FloatField()),
                ('vertex_count', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('drawn', 'Drawn on the map'), ('shapefile', 'Imported shapefile')], default='drawn', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boundary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
