# Generated by Django 5.2.17 on 2026-10-02 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=80)),
                ('species', models.CharField(blank=True, max_length=40)),
                ('district', models.CharField(max_length=60)),
                ('province', models.CharField(blank=True, max_length=60)),
                ('centre_lat', models.FloatField()),
                ('centre_lon', models.FloatField()),
                ('control_radius_km', models.FloatField(default=20, help_text='Reported control or vaccination radius.')),
                ('surveillance_radius_km', models.FloatField(default=40, help_text='Assumed surveillance ring (set by DVS).')),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('closed', 'Closed')], default='verified', max_length=10)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('source_url', models.URLField(blank=True)),
                ('location_quality', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OutbreakReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=40)),
                ('suspected', models.CharField(blank=True, max_length=80)),
                ('count', models.PositiveIntegerField(default=1)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
